[buildPlans.Template]
family = "Template"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.Template.variants.design]
capital-b = "standard-interrupted-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-p = "open-serifless"
capital-q = "crossing-baseline"
capital-r = "straight-open-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-earless-corner"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
long-s = "bent-hook-tailed"
one = "base"
six = "open-contour"
seven = "straight-serifed"
eight = "crossing-asymmetric"
nine = "open-contour"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
dollar = "interrupted-cap"
cent = "open"
lig-ltgteq = "slanted"

[buildPlans.Template.variants.italic]
capital-a = "curly-serifless"
capital-b = "standard-interrupted-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-k = "curly-serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-p = "open-serifless"
capital-q = "horizontal-tailed"
capital-r = "curly-open-serifless"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-earless-corner"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
v = "curly-serifless"
w = "curly-serifless"
x = "curly-serifless"
z = "curly-serifless"
long-s = "bent-hook-tailed"
one = "no-base"
six = "open-contour"
seven = "bend-serifed"
eight = "crossing-asymmetric"
nine = "open-contour"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
dollar = "interrupted-cap"
cent = "open"
lig-ltgteq = "slanted"

  [buildPlans.Template.ligations]
  inherits = "dlig"


[buildPlans.Template.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Template.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Template.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
