name: Build Fonts

on:
  # at 00:00 UTC on 1st of every month
  # schedule: [{cron: "0 0 1 * *"}]
  push:
    paths:
      - 'packages/iosevka/**'
      - '.github/workflows/iosevka.yml'
    branches-ignore: [ main ]
  workflow_dispatch:

env:
  template: packages/iosevka/template.toml
  iosevka: packages/iosevka/Iosevka
  dist: packages/iosevka/Iosevka/dist
  cwd: packages/iosevka


jobs:
  build:
    name: Build Iosevka
    strategy:
      matrix:
        plan: [iosevka, iosevka-extended]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: tree -L 3 -I node_modules
      - name: Generate build plans
        run: ${{ env.cwd }}/iosevka.sh ${{ env.template }}

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with: { packages: ttfautohint, version: 1.0 }

      - name: Clone Iosevka and copy build plans
        run: |
          git clone https://github.com/be5invis/Iosevka.git ${{ env.iosevka }} --depth 1
          cp ${{ env.cwd }}/${{ matrix.plan }}.toml ${{ env.iosevka }}/private-build-plans.toml


      - uses: oven-sh/setup-bun@v1

      - name: Build ${{ matrix.plan }}
        run: |
          cd ${{ env.iosevka }}
          bun install && bun run build -- contents::${{ matrix.plan }}

      # - name: Delete Oblique/Condensed
      #   run: find \( -name '*Oblique*' -or -name '*Condensed*' \) -delete

      - run: tree ${{ env.dist }}/${{ matrix.plan }}

      - name: Upload TTF
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.plan }}-ttf
          path: ${{ env.dist }}/${{ matrix.plan }}/TTF/*

      - name: Upload WOFF2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.plan }}-woff2
          path: |
            ${{ env.dist }}/${{ matrix.plan }}/${{ matrix.plan }}.css
            ${{ env.dist }}/${{ matrix.plan }}/woff2/*

  patch-iosevka:
    name: Patch Nerd Font
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plan: [iosevka, iosevka-extended]
    steps:
      - uses: actions/checkout@v2

      - name: Download ${{ matrix.plan }} TTF
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.plan }}-ttf
          path: ${{ matrix.plan }}-ttf

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with: { packages: fontforge python3-fontforge }
      - name: Download font patcher
        run: |
          curl -LO https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip
          unzip -n FontPatcher.zip

      - name: Patch nerd fonts
        run: find ${{ matrix.plan }}-ttf -name '*.ttf' -exec fontforge -script ./font-patcher {} -c -q -out ${{ matrix.plan }}-ttf-nf \;

      - run: tree ${{ matrix.plan }}-ttf-nf

      - name: Change font names
        # run: fontforge -script ${{ env.cwd }}/unrename.py ${{ matrix.plan }}-ttf-nf ttf-nf 2> /dev/null
        run: find ${{ matrix.plan }}-ttf-nf -name '*.ttf' | xargs -It {} fontforge -script ${{ env.cwd }}/unrename.py {} ttf-nf

      - name: List files
        run: tree ttf-nf

      - name: Upload TTF NF artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.plan }}-ttf-nf
          path: ttf-nf/*
