name: Build Fonts

on:
  # at 00:00 UTC on 1st of every month
  # schedule: [{cron: "0 0 1 * *"}]
  push:
    # paths:
    #   - 'packages/iosevka/**'
    #   - '.github/workflows/iosevka.yml'
    branches-ignore: [ main ]
  workflow_dispatch:

env:
  template: packages/iosevka/template.toml
  iosevka: packages/iosevka/Iosevka
  dist: packages/iosevka/Iosevka/dist
  cwd: packages/iosevka


jobs:
  build:
    name: Build Iosevka
    strategy:
      matrix:
        plan: [iosevka, iosevka-extended]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Iosevka
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.iosevka }}
          key: ${{ matrix.plan }}-${{ hashFiles(env.template) }}
      - run: tree -L 3 -I node_modules
      - name: Generate build plans
        if: steps.cache.outputs.cache-hit != 'true'
        run: ${{ env.cwd }}/iosevka.sh ${{ env.template }}

      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: steps.cache.outputs.cache-hit != 'true'
        with: { packages: ttfautohint, version: 1.0 }

      - name: Clone Iosevka and copy build plans
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/be5invis/Iosevka.git ${{ env.iosevka }} --depth 1
          cp ${{ env.cwd }}/${{ matrix.plan }}.toml ${{ env.iosevka }}/private-build-plans.toml

      - uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with: { node-version: 'latest' }

      - name: Build ${{ matrix.plan }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ${{ env.iosevka }}
          npm ci && npm run build -- contents::${{ matrix.plan }}

      - name: Upload TTF
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.plan }}-ttf
          path: ${{ env.dist }}/${{ matrix.plan }}/ttf/*

      - name: Upload WOFF2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.plan }}-woff2
          path: |
            ${{ env.dist }}/${{ matrix.plan }}/${{ matrix.plan }}.css
            ${{ env.dist }}/${{ matrix.plan }}/woff2/*

  # upload:
  #   name: Upload Fonts as Artifact
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: iosevka-woff2
  #         path: ${{ env.iosevka }}

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: iosevka-extended-woff2
  #         path: ${{ env.iosevka }}

  #     - name: No TTF Fonts
  #       run: perl -i -pe "s/url\('ttf\/.+,\s*//g" ${{ env.iosevka }}/*.css

  #     - run: tree ${{ env.iosevka }}

  #     - uses: actions/upload-artifact@v2
  #       name: fonts
  #       with:
  #         path: ${{ env.iosevka }}

  # deploy:
  #   needs: upload
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1

  patch-iosevka:
    name: Patch Nerd Font
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plan: [iosevka, iosevka-extended]
    defaults:
      run:
        working-directory: ${{ env.cwd }}
    steps:
      - uses: actions/checkout@v2

      - name: Download ${{ matrix.plan }} WOFF2
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.plan }}-woff2
          path: ${{ env.cwd }}/woff2

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with: { packages: fontforge python3-fontforge }

      - run: find -name '*.woff2'

      - name: Download patcher
        run: |
          curl -LO https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip
          unzip FontPatcher.zip
      - name: Patch nerd fonts
        run: |
          for f in `find -name '*.woff2'`; do
              echo $f
              ./font-patcher "$f" -c -q --no-progressbars -out nerd
          done

      - run: tree -I nerd-fonts

      - name: Change font names
        run: fontforge unrename.py nerd woff2-nf

      - name: List files
        run: tree -I nerd-fonts

      - name: Upload WOFF2 NF artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.plan }}-woff2-nf
          path: ${{ env.cwd }}/woff2-nf/*
